version: '2.4'

services:
  gateway:
    image: dayu/dayu-gateway:latest
    container_name: dayu-gateway
    hostname: gateway
    restart: always
    cpus: 1
    mem_limit: 2G
    privileged: true
    networks:
      - dayu-net
    ports:
      - 8080:8080
    

  management:
    image: dayu.com:5453/dayu/dayu-management:1.2-daily-202001201534
    container_name: dayu-management
    hostname: management
    restart: always
    cpus: 1
    mem_limit: 1G
    privileged: true
    networks:
      - dayu-net

  consul:
    image: consul:latest
    container_name: dayu-consul
    hostname: consul
    restart: always
    cpus: 2
    mem_limit: 2G
    privileged: true
    networks:
      - dayu-net
    ports:
      - 8500:8500
      - 8300:8300
    volumes:
      - consul-data:/consul

  timescaledb:
    image: timescale/timescaledb:latest-pg11
    container_name: dayu-timescaledb
    hostname: timescaledb
    restart: always
    cpus: 8
    mem_limit: 8G
    privileged: true
    environment:
      - POSTGRES_PASSWORD=123456
    networks:
      - dayu-net
    ports:
      - 5432:5432
    volumes:
      - ts-data:/var/lib/postgresql/data

   

  prometheus:
    image: prom/prometheus:latest
    container_name: dayu-prometheus
    hostname: prometheus
    cpus: 2
    mem_limit: 2G
    privileged: true
    ports:
      - 9090:9090
    volumes:
      - /media/leus/data/develops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - dayu-net

  master-node:
    image: prom/node-exporter:latest
    container_name: dayu-master-node
    hostname: master-node
    cpus: 2
    mem_limit: 2G
    privileged: true
  # network_mode: host
    networks:
      - dayu-net
    ports:
      - 9100:9100
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/:/rootfs:ro"

  grafana:
    image: grafana/grafana:latest
    container_name: dayu-grafana
    hostname: grafana
    cpus: 2
    mem_limit: 2G
    privileged: true
    # network_mode: host
    networks:
      - dayu-net
    ports:
      - 3000:3000
    volumes:
      - "/media/leus/data/develops/grafana-storage:/var/lib/grafana"




volumes:
   ts-data:
   consul-data:

networks:
  dayu-net:
    external: false


